[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
ubalance_prediction_market = "FkZVTshsawSNHYzxFZFfdBJUbLxvQJVhWtJqi8FgunFG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "echo \"add anchor tests\""
